### ISSUE TITLE
Private Compose Hub Server

### ISSUE THREAD

**Issue by davidkbainbridge** [composehub/cli#3]
Couldn't find a compose file to run a private instance of the composehub server. Is this possible? I see the endpoint can be specified via an env var, but didn't see how to start your own server. Unfortunately not everything can be public.

**Comment by patcito** [comment]
You can make your own packages private by setting private: true in your composehub.yml and they won't be discoverable publicly, no need to run your own server. You can also run your own server though if you need https://github.com/composehub/server.
